# Generated by Django 5.1.4 on 2024-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardscategorymodel_alter_cardsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsmodel',
            name='category',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='CardsCategoryModel',
        ),
    ]
